/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                "#3525cd",
        "primary-container":      "#4f46e5",
        "primary-fixed":          "#e0deff",
        "primary-fixed-dim":      "#c3c0ff",
        "surface":                "#fafaff",
        "surface-container-low":  "#f3f4fb",
        "surface-container":      "#edeef6",
        "surface-variant":        "#e4e5ef",
        "on-surface":             "#191c1e",
        "on-surface-variant":     "#464555",
        "outline":                "#777587",
        "border-slate":           "#E2E8F0",
        "outline-variant":        "#d9dce5",
        "status-emerald-bg":      "#ECFDF5",
        "status-emerald-text":    "#059669",
        "status-amber-bg":        "#FFFBEB",
        "status-amber-text":      "#D97706",
        "status-rose-bg":         "#FFF1F2",
        "status-rose-text":       "#E11D48",
        "glass-surface":          "rgba(255,255,255,0.8)",
        "background":             "#f6f6ff",
        /* extras used by modals / toast / transmittals */
        "on-primary":             "#ffffff",
        "secondary":              "#565e74",
        "error":                  "#b3261e",
        "error-container":        "#f9dedc",
        "on-error-container":     "#410e0b",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest":"#ffffff",
        "on-background":          "#191c1e",
        "inverse-primary":        "#c3c0ff",
      },
      fontFamily: {
        "outfit":        ["Outfit", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
        /* display + top-level headlines → Space Grotesk; body/label roles → Outfit */
        "display-lg":    ["Space Grotesk", "sans-serif"],
        "headline-lg":   ["Space Grotesk", "sans-serif"],
        /* body / label roles stay Outfit */
        "headline-md": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "label-md":    ["Outfit", "sans-serif"],
        "label-sm":    ["Outfit", "sans-serif"],
        "body-md":     ["Outfit", "sans-serif"],
        "body-sm":     ["Outfit", "sans-serif"],
        "sans":        ["Outfit", "sans-serif"],
      },
      fontSize: {
        "label-md":    ["12px", { lineHeight: "1",   letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm":    ["11px", { lineHeight: "1",                             fontWeight: "500" }],
        "body-sm":     ["14px", { lineHeight: "20px",                          fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "24px",                          fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "1.4",                           fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px",                          fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em",fontWeight: "600" }],
        "display-lg":  ["48px", { lineHeight: "1.1",  letterSpacing: "-0.02em",fontWeight: "700" }],
      },
      spacing: {
        "sidebar-width":  "280px",
        "margin-desktop": "40px",
      },
      boxShadow: {
        /* 3-step card elevation — referenced across the app but never defined. */
        "card":    "0 1px 2px rgba(16, 24, 40, 0.04), 0 1px 3px rgba(16, 24, 40, 0.06)",
        "card-md": "0 4px 12px rgba(16, 24, 40, 0.06), 0 2px 4px rgba(16, 24, 40, 0.04)",
        "card-lg": "0 8px 30px rgba(16, 24, 40, 0.08), 0 2px 6px rgba(16, 24, 40, 0.04)",
      },
    },
  },
  plugins: [],
};
