/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdbcc",
        "outline-variant": "#464555",
        "on-tertiary-fixed": "#351000",
        "inverse-on-surface": "#283044",
        "surface-container-high": "#222a3d",
        "on-secondary-fixed": "#191c1e",
        "on-error": "#690005",
        "secondary-container": "#464a4b",
        "on-tertiary": "#571f00",
        "tertiary-container": "#a44100",
        "on-secondary-container": "#b6b9bb",
        "surface-variant": "#2d3449",
        "on-tertiary-container": "#ffd2be",
        "on-tertiary-fixed-variant": "#7b2f00",
        "primary-container": "#4f46e5",
        "primary": "#c3c0ff",
        "surface": "#0b1326",
        "tertiary": "#ffb695",
        "outline": "#918fa1",
        "inverse-surface": "#dae2fd",
        "surface-tint": "#c3c0ff",
        "on-surface": "#dae2fd",
        "on-secondary": "#2d3133",
        "primary-fixed": "#e2dfff",
        "surface-dim": "#0b1326",
        "surface-container-lowest": "#060e20",
        "on-primary-container": "#dad7ff",
        "surface-container-low": "#131b2e",
        "error-container": "#93000a",
        "background": "#0b1326",
        "inverse-primary": "#4d44e3",
        "on-secondary-fixed-variant": "#444749",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-highest": "#2d3449",
        "secondary": "#c4c7c9",
        "on-error-container": "#ffdad6",
        "surface-bright": "#31394d",
        "secondary-fixed": "#e0e3e5",
        "on-background": "#dae2fd",
        "on-primary-fixed": "#0f0069",
        "error": "#ffb4ab",
        "surface-container": "#171f33",
        "on-surface-variant": "#c7c4d8",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed-dim": "#c4c7c9",
        "tertiary-fixed-dim": "#ffb695",
        "on-primary": "#1d00a5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "max-width": "1600px",
        "unit": "4px",
        "gutter": "24px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "label-md": ["Outfit"],
        "headline-lg": ["Outfit"],
        "body-md": ["Outfit"],
        "label-sm": ["Outfit"],
        "headline-md": ["Outfit"],
        "body-lg": ["Outfit"],
        "body-sm": ["Outfit"],
        "headline-sm": ["Outfit"],
        "headline-lg-mobile": ["Outfit"],
        "display-lg": ["Outfit"],
        "sans": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "1", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}